web:
  build: .
  volumes:
    - .:/app
    - '/Users/erjhome/volumes/lb2geo/efs:/var/lib/efs'
  ports:
    - "3000:3000"
  links:
    - db
    - gblsolr
  env_file:
    - '.env.web'
db:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  env_file:
    - '.env.db'
  volumes:
    - '/Users/erjhome/volumes/lb2geo/mysql:/var/lib/mysql'
geoblacklight:
  image: geoblacklight/geoblacklight
  ports:
    - "3001:3000"
  links:
    - gblsolr
  environment:
    - SOLR_URL=http://gblsolr:8983/solr/geoblacklight
gblsolr:
  image: geoblacklight/solr
  expose:
    - "8983"
  ports:
    - "9983:8983"
  volumes:
    - '/Users/erjhome/volumes/lb2geo/solr/data:/var/solr/data/geoblacklight/data'
