web:
  build: .
  volumes:
    - .:/app
    - '/Users/erjhome/volumes/lb2geo/efs:/var/lib/efs'
  ports:
    - "3000:3000"
  links:
    - db
  env_file:
    - '.env.web'
db:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  env_file:
    - '.env.db'
  volumes:
    - '/Users/erjhome/volumes/lb2geo/mysql:/var/lib/mysql'
